services:
  node-app:
    build: ./node-app
    container_name: node-docker-app
    ports:
      - "3200:8080"   # changed external port from 8080 → 3200
    environment:
      - NODE_ENV=production
    restart: always

  python-app:
    build: ./python-app
    container_name: flask-docker-app
    ports:
      - "5000:8080"
    restart: always

  python-sqlite-app:
    build: ./python-sqllite-app
    container_name: flask-sqlite-app
    ports:
      - "6000:6060"
    restart: always
