name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 👇 Note the "-f examples/docker-compose.yml"
      - name: Build all Docker services
        run: docker compose -f examples/docker-compose.yml build

      - name: Run containers
        run: docker compose -f examples/docker-compose.yml up -d

      - name: Wait for containers to start
        run: sleep 10

      - name: Check running containers
        run: docker ps

      - name: Test endpoints (example)
        run: |
          curl -f http://localhost:3200 || exit 1
          curl -f http://localhost:5000 || exit 1
          curl -f http://localhost:6000 || exit 1

      - name: Stop containers
        run: docker compose -f examples/docker-compose.yml down
