name: Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          echo "✅ Running unit tests..."
          pytest || echo "⚠️ Tests failed, but continuing pipeline"

      - name: Lint code (optional)
        run: |
          echo "🧹 Running flake8 lint checks..."
          pip install flake8
          flake8 . || echo "⚠️ Lint warnings found"

      - name: Build Docker images (optional sanity check)
        run: |
          echo "🐳 Building Docker images for validation..."
          docker compose -f examples/docker-compose.yml build
